# the builtin.grep_string called by leader fs wasnt working, this fixed it for mac

brew install ripgrep

# packer plugin manager
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
        ~/.local/share/nvim/site/pack/packer/start/packer.nvim

# rocks plugin manager
        nvim -u NORC -c "source https://raw.githubusercontent.com/nvim-neorocks/rocks.nvim/master/installer.lua"
# follow instructions
# brew install lua

# for rust lsp
        :Rocks install rustaceanvim

# install rust-analyzer
# sudo mv rust-analyzer-aarch64-apple-darwin /usr/local/bin/rust-analyzer
# instead i now did
        rustup component add rust-analyzer

# install node
        brew install node

        npm install -g neovim

# python lsp
# npm install -g pyright

# inside a venv, and point nvim to that python3 bin
        pip3 install pyvim
        pip3 install neovim

# maybe add  _signs_staged_enable = true, -- This might have enabled the unstaging of Gitsings diffview setup
# this is also done in diffview.lua, so its probably not needed anymore 
# todo: https://www.naseraleisa.com/posts/diff


# vim.opt_local.wrap = false in diffview see their github

brew install font-hack-nerd-font 
# set is as font in the terminal

brew install lua-language-server

nvim-treesitter/playground
:TSInstall query

# after installing copilot (see packer), run :copilot setup
# did download the arm64 5.1 from https://github.com/gptlang/lua-tiktoken/releases and put it in (with the name "tiktoken_core.so") /opt/homebrew/lib/lua/5.1 (and just to be safe also in /usr/local/lib/lua/5.4). then upon running it said sth like "downloading tiktoken" 


brew install fd

what was the plugin or setting that makes the same words as under the cursor highlighted?

