require("mattes.remap")
require("mattes.packer")
require("mattes.rust")
require("mattes.gitsigns")
require("mattes.trouble")
require("mattes.diffview")
-- require("mattes.unstage_hunk")
require("mattes.find_enclosing")
require("mattes.symbols_with_custom")
require("mattes.color")
--require("mattes.tiny_diagnostics")
require("mattes.diagnostics")
